# Generated by Django 3.1.2 on 2020-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('progress', models.FloatField()),
                ('stage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[(1, 'Genius by Default'), (2, 'Ultra Learner'), (3, 'All Rounder'), (4, 'Techy'), (5, 'Dummy')], max_length=100)),
                ('logic', models.IntegerField()),
                ('creativity', models.IntegerField()),
                ('calculation', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('efficiency', models.IntegerField()),
            ],
        ),
    ]
