# Generated by Django 3.1.2 on 2020-11-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(choices=[('1', 'Dummy'), ('2', 'Techy'), ('3', 'All Rounder'), ('4', 'Ultra Learner'), ('5', 'Mad Genius')], default='5', max_length=100),
        ),
    ]
